namespace Free.Schema;

public enum OverrideType : byte
{
    Unknown = 0,
    NestedComponent = 1,
    StringValue = 2,
    TextStyle = 3,
    LayerStyle = 4,
    Image = 5,
    Hotspot = 6,
    Tint = 7,
    Color = 8,
    TextColor = 9,
    TextWeight = 10,
    CornerRadius = 11,
    Fills = 12,
    Borders = 13,
    BorderOptions = 14,
    Effects = 15,
    Blending = 16,
    Typography = 17,
    ExportOptions = 18,
    Lock = 19,
    Visibility = 20,
    ClipContent = 21,
    RadiusBehavior = 22,
    StartArrowhead = 23,
    EndArrowhead = 24,
    LayoutOrientation = 25,
    LayoutSpacing = 26,
    LayoutPadding = 27,
    LayoutAlign = 28,
    LayoutSizing = 29,
    LayoutTextBaseline = 30,
    LayoutIncludeBorders = 31,
    LayoutReverseZIndex = 32,
    LayoutStretch = 33,
    Arc = 34,
    LayoutWrap = 35,
    LayoutWrapDistribute = 36,
    LayoutWrapSpacing = 37,
    LockAspect = 38,
    StarRatio = 39,
    VertexCount = 40,
    LayoutMinMax = 41,
    ImageFilters = 42,
}